# subsystems/echo/consolidation.py
"""
ECHO v1 Memory Consolidation Engine.

Implements :class:`MemoryConsolidationEngine` — the production implementation
of :class:`~subsystems.echo.interfaces.MemoryConsolidationEngineInterface`.

Consolidation converts short-term experience records into long-term memory by:

1. **Promotion**  — elevating unconsolidated MEDIUM+ experiences into the
   long-term tier by calling :meth:`ExperienceMetadata.mark_consolidated`.
2. **Pruning**    — removing LOW-importance records that have not been
   retrieved recently and fall below retention thresholds.
3. **Archiving**  — permanently flagging CRITICAL records so they survive
   all future pruning sweeps.
4. **Reflection integration** — incorporating synthesised reflections
   generated by the Reflection Engine into consolidated memory.
5. **Significance integration** — re-scoring experiences at consolidation
   time so that significance drift is captured before long-term storage.

Consolidation Policies
----------------------
* ``CRITICAL`` experiences are **never** pruned and are always marked
  consolidated on first encounter.
* ``HIGH`` experiences are promoted unconditionally.
* ``MEDIUM`` experiences are promoted when they meet the significance
  threshold OR have been retrieved at least once.
* ``LOW`` experiences are pruned after ``low_retention_days`` unless
  they have been retrieved within ``low_retrieval_grace_days``.

Thread Safety
-------------
All public methods acquire ``self._lock`` (a :class:`threading.RLock`)
before accessing shared mutable state.

Scheduling
----------
The engine exposes :meth:`run_consolidation_cycle` for on-demand execution
and does not internally schedule background runs.  Callers (e.g. the ECHO
subsystem orchestrator or a :mod:`threading.Timer`) are responsible for
scheduling cycles at appropriate intervals.
"""

from __future__ import annotations

import logging
import threading
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any

from subsystems.echo.exceptions import (
    EchoNotInitializedError,
    ExperienceNotFoundError,
)
from subsystems.echo.interfaces import (
    ExperienceEngineInterface,
    MemoryConsolidationEngineInterface,
    SignificanceEngineInterface,
)
from subsystems.echo.models import (
    Experience,
    ExperienceImportance,
    ExperienceType,
)

_logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Default policy constants
# ---------------------------------------------------------------------------

_DEFAULT_LOW_RETENTION_DAYS: int = 30
"""Days a LOW experience lives before becoming a prune candidate."""

_DEFAULT_LOW_RETRIEVAL_GRACE_DAYS: int = 7
"""LOW experiences retrieved within this window are exempt from pruning."""

_DEFAULT_MIN_SIGNIFICANCE_FOR_MEDIUM: float = 0.20
"""Minimum significance score for a MEDIUM experience to be promoted."""

_DEFAULT_MIN_RETRIEVAL_FOR_MEDIUM: int = 1
"""Alternative promotion gate: MEDIUM experiences retrieved this many times
are promoted regardless of significance score."""

_DEFAULT_CYCLE_CANDIDATE_LIMIT: int = 500
"""Maximum experiences evaluated per consolidation cycle."""


# ---------------------------------------------------------------------------
# Consolidation Policy Dataclass
# ---------------------------------------------------------------------------


@dataclass
class ConsolidationPolicy:
    """Tunable parameters for :class:`MemoryConsolidationEngine`.

    All time parameters are in days.  All thresholds are in [0.0, 1.0].

    Attributes
    ----------
    low_retention_days:
        Age (days) at which a LOW-importance experience becomes a prune
        candidate.
    low_retrieval_grace_days:
        A LOW experience retrieved within this window (relative to now)
        is exempt from pruning regardless of age.
    min_significance_for_medium:
        Significance score floor for promoting a MEDIUM experience to
        long-term memory without a retrieval count.
    min_retrieval_for_medium:
        Minimum retrieval count for promoting a MEDIUM experience when
        it does not meet the significance floor.
    promote_reflections:
        If ``True``, REFLECTION experiences are always promoted to
        long-term memory, bypassing the significance gate.
    promote_achievements:
        If ``True``, ACHIEVEMENT experiences are always promoted.
    prune_low:
        If ``False``, LOW experiences are never pruned (useful for
        debugging or data-preservation modes).
    cycle_candidate_limit:
        Maximum number of experiences evaluated in a single cycle.
    """

    low_retention_days: int = _DEFAULT_LOW_RETENTION_DAYS
    low_retrieval_grace_days: int = _DEFAULT_LOW_RETRIEVAL_GRACE_DAYS
    min_significance_for_medium: float = _DEFAULT_MIN_SIGNIFICANCE_FOR_MEDIUM
    min_retrieval_for_medium: int = _DEFAULT_MIN_RETRIEVAL_FOR_MEDIUM
    promote_reflections: bool = True
    promote_achievements: bool = True
    prune_low: bool = True
    cycle_candidate_limit: int = _DEFAULT_CYCLE_CANDIDATE_LIMIT

    def __post_init__(self) -> None:
        if self.low_retention_days < 1:
            raise ValueError("low_retention_days must be >= 1.")
        if not (0.0 <= self.min_significance_for_medium <= 1.0):
            raise ValueError(
                "min_significance_for_medium must be in [0.0, 1.0]."
            )


# ---------------------------------------------------------------------------
# Consolidation Report
# ---------------------------------------------------------------------------


@dataclass
class ConsolidationReport:
    """Summary produced by each :meth:`MemoryConsolidationEngine.run_consolidation_cycle` call.

    Attributes
    ----------
    cycle_started_at:
        UTC timestamp when the cycle began.
    cycle_finished_at:
        UTC timestamp when the cycle completed (``None`` if still running).
    candidates_evaluated:
        Total experiences examined.
    promoted:
        IDs of experiences promoted to long-term memory.
    pruned:
        IDs of experiences removed by retention policy.
    archived:
        IDs of CRITICAL experiences permanently archived.
    skipped:
        Count of experiences skipped for any reason (already consolidated,
        below threshold and not prunable, etc.).
    errors:
        List of (experience_id, error_message) tuples for any failures.
    """

    cycle_started_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    cycle_finished_at: datetime | None = None
    candidates_evaluated: int = 0
    promoted: list[str] = field(default_factory=list)
    pruned: list[str] = field(default_factory=list)
    archived: list[str] = field(default_factory=list)
    skipped: int = 0
    errors: list[tuple[str, str]] = field(default_factory=list)

    def finish(self) -> None:
        """Mark the cycle as complete."""
        self.cycle_finished_at = datetime.now(timezone.utc)

    @property
    def promoted_count(self) -> int:
        """Number of experiences promoted to long-term memory in this cycle."""
        return len(self.promoted)

    @property
    def pruned_count(self) -> int:
        """Number of experiences pruned in this cycle."""
        return len(self.pruned)

    @property
    def duration_seconds(self) -> float | None:
        """Return cycle duration in seconds, or ``None`` if not finished."""
        if self.cycle_finished_at is None:
            return None
        return (
            self.cycle_finished_at - self.cycle_started_at
        ).total_seconds()

    @property
    def total_actions(self) -> int:
        """Total number of experiences that were acted upon."""
        return len(self.promoted) + len(self.pruned) + len(self.archived)

    def summary(self) -> str:
        """Return a one-line human-readable summary."""
        dur = f"{self.duration_seconds:.2f}s" if self.duration_seconds is not None else "?"
        return (
            f"ConsolidationCycle: evaluated={self.candidates_evaluated} "
            f"promoted={len(self.promoted)} pruned={len(self.pruned)} "
            f"archived={len(self.archived)} skipped={self.skipped} "
            f"errors={len(self.errors)} duration={dur}"
        )


# ---------------------------------------------------------------------------
# MemoryConsolidationEngine
# ---------------------------------------------------------------------------


class MemoryConsolidationEngine(MemoryConsolidationEngineInterface):
    """Production implementation of the ECHO Memory Consolidation Engine.

    Parameters
    ----------
    experience_engine:
        A running :class:`~subsystems.echo.interfaces.ExperienceEngineInterface`
        whose store is managed by consolidation operations.
    significance_engine:
        A running :class:`~subsystems.echo.interfaces.SignificanceEngineInterface`
        used to re-score experiences at consolidation time.
    policy:
        :class:`ConsolidationPolicy` controlling retention and promotion
        thresholds.  Defaults to :class:`ConsolidationPolicy` with all
        default values.

    Usage
    -----
    ::

        engine = MemoryConsolidationEngine(
            experience_engine=exp_engine,
            significance_engine=sig_engine,
        )
        engine.initialize()
        report = engine.run_consolidation_cycle()
        print(report.summary())
        engine.shutdown()
    """

    def __init__(
        self,
        experience_engine: ExperienceEngineInterface,
        significance_engine: SignificanceEngineInterface,
        *,
        policy: ConsolidationPolicy | None = None,
    ) -> None:
        self._experience_engine = experience_engine
        self._significance_engine = significance_engine
        self._policy: ConsolidationPolicy = policy or ConsolidationPolicy()

        # Audit log: list of completed ConsolidationReport objects
        self._cycle_history: list[ConsolidationReport] = []

        self._lock: threading.RLock = threading.RLock()
        self._running: bool = False

        _logger.debug("MemoryConsolidationEngine constructed.")

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def initialize(self) -> None:
        """Prepare the engine for use."""
        with self._lock:
            if self._running:
                _logger.warning(
                    "MemoryConsolidationEngine.initialize() called while already running."
                )
                return
            self._running = True
            _logger.info("MemoryConsolidationEngine initialised.")

    def shutdown(self) -> None:
        """Release resources and stop the engine."""
        with self._lock:
            if not self._running:
                return
            self._running = False
            _logger.info(
                "MemoryConsolidationEngine shut down. %d cycle(s) completed.",
                len(self._cycle_history),
            )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _assert_running(self, operation: str) -> None:
        """Raise :class:`EchoNotInitializedError` if not running."""
        if not self._running:
            raise EchoNotInitializedError(operation)

    def _publish_event(self, event_name: str, payload: dict[str, Any]) -> None:
        """Emit a domain event (logged at DEBUG in v1)."""
        _logger.debug("ECHO domain event: %s — %s", event_name, payload)

    def _rescore(self, experience: Experience) -> float:
        """Re-evaluate significance score for *experience*.

        Falls back to the stored score if scoring fails (non-fatal).
        """
        try:
            result = self._significance_engine.score_experience(experience)
            return result.score
        except Exception as exc:  # noqa: BLE001
            _logger.warning(
                "Re-scoring failed for %s (%s); using stored score %.3f.",
                experience.experience_id,
                exc,
                experience.metadata.significance_score,
            )
            return experience.metadata.significance_score

    def _is_prune_candidate(
        self,
        experience: Experience,
        now: datetime,
    ) -> bool:
        """Return ``True`` if *experience* should be pruned under current policy."""
        if not self._policy.prune_low:
            return False
        if experience.importance != ExperienceImportance.LOW:
            return False
        if experience.is_permanent():
            return False

        age_days = (now - experience.occurred_at).total_seconds() / 86400.0
        if age_days < self._policy.low_retention_days:
            return False

        # Grace period: recently retrieved LOW experiences survive
        if experience.metadata.last_retrieved_at is not None:
            last_ret = experience.metadata.last_retrieved_at
            grace_cutoff = now - timedelta(days=self._policy.low_retrieval_grace_days)
            if last_ret >= grace_cutoff:
                return False

        return True

    def _is_promote_candidate(
        self,
        experience: Experience,
        rescored_significance: float,
    ) -> bool:
        """Return ``True`` if *experience* qualifies for long-term promotion."""
        if experience.metadata.consolidated:
            return False  # Already done

        importance = experience.importance

        if importance == ExperienceImportance.CRITICAL:
            return True

        if importance == ExperienceImportance.HIGH:
            return True

        if importance == ExperienceImportance.MEDIUM:
            # Promote via significance threshold OR retrieval count
            if rescored_significance >= self._policy.min_significance_for_medium:
                return True
            if (
                experience.metadata.retrieval_count
                >= self._policy.min_retrieval_for_medium
            ):
                return True
            # Type-based overrides
            if (
                self._policy.promote_reflections
                and experience.experience_type == ExperienceType.REFLECTION
            ):
                return True
            if (
                self._policy.promote_achievements
                and experience.experience_type == ExperienceType.ACHIEVEMENT
            ):
                return True
            return False

        # LOW experiences are never promoted (only pruned or kept short-term)
        return False

    def _promote(
        self,
        experience: Experience,
        report: ConsolidationReport,
    ) -> None:
        """Mark *experience* as consolidated and update metadata."""
        experience.metadata.significance_score = self._rescore(experience)
        experience.metadata.mark_consolidated()
        report.promoted.append(experience.experience_id)
        self._publish_event(
            "ExperienceConsolidated",
            {
                "experience_id": experience.experience_id,
                "title": experience.title,
                "importance": experience.importance.name,
                "significance_score": experience.metadata.significance_score,
            },
        )
        _logger.debug(
            "Promoted experience %s (%s) to long-term memory.",
            experience.experience_id,
            experience.title,
        )

    def _archive(
        self,
        experience: Experience,
        report: ConsolidationReport,
    ) -> None:
        """Permanently archive a CRITICAL experience (always consolidated)."""
        if not experience.metadata.consolidated:
            experience.metadata.mark_consolidated()
        report.archived.append(experience.experience_id)
        self._publish_event(
            "ExperienceArchived",
            {
                "experience_id": experience.experience_id,
                "title": experience.title,
            },
        )
        _logger.debug(
            "Archived CRITICAL experience %s.", experience.experience_id
        )

    def _prune(
        self,
        experience: Experience,
        report: ConsolidationReport,
    ) -> None:
        """Remove *experience* from the store."""
        try:
            self._experience_engine.delete_experience(experience.experience_id)
            report.pruned.append(experience.experience_id)
            self._publish_event(
                "ExperiencePruned",
                {
                    "experience_id": experience.experience_id,
                    "title": experience.title,
                    "importance": experience.importance.name,
                },
            )
            _logger.debug(
                "Pruned LOW experience %s (%s).",
                experience.experience_id,
                experience.title,
            )
        except Exception as exc:  # noqa: BLE001
            report.errors.append((experience.experience_id, str(exc)))
            _logger.error(
                "Failed to prune experience %s: %s",
                experience.experience_id,
                exc,
            )

    # ------------------------------------------------------------------
    # Public API — interface contract
    # ------------------------------------------------------------------

    def run_consolidation_cycle(self) -> ConsolidationReport:
        """Execute one full consolidation cycle.

        Iterates over all experiences (up to ``policy.cycle_candidate_limit``),
        archiving CRITICAL records, promoting eligible MEDIUM+ records, and
        pruning expired LOW records.

        Returns
        -------
        ConsolidationReport
            Summary of this cycle's actions.
        """
        with self._lock:
            self._assert_running("run_consolidation_cycle")

            report = ConsolidationReport()
            now = datetime.now(timezone.utc)

            candidates = self._experience_engine.query_experiences()
            # Stable sort: CRITICAL first, then HIGH, MEDIUM, LOW
            _order = {
                ExperienceImportance.CRITICAL: 0,
                ExperienceImportance.HIGH: 1,
                ExperienceImportance.MEDIUM: 2,
                ExperienceImportance.LOW: 3,
            }
            candidates.sort(key=lambda e: _order[e.importance])

            # Apply candidate limit
            candidates = candidates[: self._policy.cycle_candidate_limit]
            report.candidates_evaluated = len(candidates)

            for exp in candidates:
                try:
                    # CRITICAL — archive unconditionally
                    if exp.importance == ExperienceImportance.CRITICAL:
                        self._archive(exp, report)
                        continue

                    # LOW — check for pruning first
                    if self._is_prune_candidate(exp, now):
                        self._prune(exp, report)
                        continue

                    # Already consolidated — skip
                    if exp.metadata.consolidated:
                        report.skipped += 1
                        continue

                    # Attempt promotion
                    rescored = self._rescore(exp)
                    exp.metadata.significance_score = rescored

                    if self._is_promote_candidate(exp, rescored):
                        self._promote(exp, report)
                    else:
                        report.skipped += 1

                except Exception as exc:  # noqa: BLE001
                    report.errors.append((exp.experience_id, str(exc)))
                    _logger.error(
                        "Consolidation error for %s: %s",
                        exp.experience_id,
                        exc,
                        exc_info=True,
                    )

            report.finish()
            self._cycle_history.append(report)

            _logger.info(report.summary())
            return report

    def consolidate_experience(self, experience_id: str) -> Experience:
        """Force-consolidate a specific experience into long-term memory.

        Skips policy gates — always promotes regardless of significance
        score or importance tier.  The only exception: CRITICAL experiences
        that are already archived receive a no-op.

        Parameters
        ----------
        experience_id:
            UUID of the experience to consolidate.

        Returns
        -------
        Experience
            The consolidated experience with updated metadata.

        Raises
        ------
        ExperienceNotFoundError
            If no experience with *experience_id* exists.
        EchoNotInitializedError
            If the engine is not running.
        """
        with self._lock:
            self._assert_running("consolidate_experience")

            experience = self._experience_engine.get_experience(experience_id)

            if not experience.metadata.consolidated:
                experience.metadata.significance_score = self._rescore(experience)
                experience.metadata.mark_consolidated()
                self._publish_event(
                    "ExperienceConsolidated",
                    {
                        "experience_id": experience.experience_id,
                        "title": experience.title,
                        "force": True,
                    },
                )
                _logger.info(
                    "Force-consolidated experience %s (%s).",
                    experience_id,
                    experience.title,
                )
            else:
                _logger.debug(
                    "consolidate_experience(%r): already consolidated; no-op.",
                    experience_id,
                )

            return experience

    def get_consolidation_candidates(
        self,
        limit: int = 100,
    ) -> list[Experience]:
        """Return experiences eligible for consolidation in the next cycle.

        Candidates are unconsolidated experiences at MEDIUM importance or
        above.

        Parameters
        ----------
        limit:
            Maximum candidates to return.

        Returns
        -------
        list[Experience]
            Unconsolidated MEDIUM+ experiences, most significant first.
        """
        with self._lock:
            self._assert_running("get_consolidation_candidates")

            _eligible_tiers = {
                ExperienceImportance.MEDIUM,
                ExperienceImportance.HIGH,
                ExperienceImportance.CRITICAL,
            }

            candidates: list[Experience] = []
            for exp in self._experience_engine.query_experiences():
                if exp.importance in _eligible_tiers and not exp.metadata.consolidated:
                    candidates.append(exp)

            # Sort by significance score desc, then by importance desc
            _imp_order = {
                ExperienceImportance.CRITICAL: 4,
                ExperienceImportance.HIGH: 3,
                ExperienceImportance.MEDIUM: 2,
                ExperienceImportance.LOW: 1,
            }
            candidates.sort(
                key=lambda e: (
                    -e.metadata.significance_score,
                    -_imp_order[e.importance],
                ),
            )
            return candidates[:limit]

    # ------------------------------------------------------------------
    # Retention Management
    # ------------------------------------------------------------------

    def get_prune_candidates(
        self,
        limit: int = 200,
    ) -> list[Experience]:
        """Return LOW-importance experiences that would be pruned in the next cycle.

        Does not perform pruning — read-only snapshot of what the cycle
        *would* remove.

        Parameters
        ----------
        limit:
            Maximum results.

        Returns
        -------
        list[Experience]
            Prune-eligible experiences ordered oldest-first.
        """
        with self._lock:
            self._assert_running("get_prune_candidates")

            now = datetime.now(timezone.utc)
            candidates = [
                exp
                for exp in self._experience_engine.query_experiences()
                if self._is_prune_candidate(exp, now)
            ]
            candidates.sort(key=lambda e: e.occurred_at)
            return candidates[:limit]

    def integrate_reflection(
        self,
        reflection_experience_id: str,
        *,
        source_experience_ids: list[str] | None = None,
    ) -> Experience:
        """Integrate a reflection experience into consolidated long-term memory.

        Reflections are always promoted regardless of their current
        consolidation state.  Their significance scores are updated and
        any provided source experiences are linked via
        :attr:`~subsystems.echo.models.ExperienceMetadata.related_experience_ids`.

        Parameters
        ----------
        reflection_experience_id:
            UUID of the REFLECTION experience to integrate.
        source_experience_ids:
            UUIDs of experiences the reflection was synthesised from.
            These are added to the reflection's ``related_experience_ids``.

        Returns
        -------
        Experience
            The updated reflection experience.

        Raises
        ------
        ExperienceNotFoundError
            If the reflection experience does not exist.
        EchoNotInitializedError
            If the engine is not running.
        """
        with self._lock:
            self._assert_running("integrate_reflection")

            reflection = self._experience_engine.get_experience(
                reflection_experience_id
            )

            if reflection.experience_type != ExperienceType.REFLECTION:
                _logger.warning(
                    "integrate_reflection called on non-REFLECTION experience %s "
                    "(type=%s); proceeding anyway.",
                    reflection_experience_id,
                    reflection.experience_type.name,
                )

            # Link sources
            if source_experience_ids:
                existing_refs = set(reflection.metadata.related_experience_ids)
                for src_id in source_experience_ids:
                    if src_id not in existing_refs:
                        reflection.metadata.related_experience_ids.append(src_id)
                        existing_refs.add(src_id)

            # Rescore and promote
            reflection.metadata.significance_score = self._rescore(reflection)
            if not reflection.metadata.consolidated:
                reflection.metadata.mark_consolidated()

            self._publish_event(
                "ReflectionIntegrated",
                {
                    "reflection_id": reflection_experience_id,
                    "source_count": len(source_experience_ids or []),
                    "significance_score": reflection.metadata.significance_score,
                },
            )
            _logger.info(
                "Integrated reflection %s into long-term memory.", reflection_experience_id
            )
            return reflection

    def integrate_significance_scores(
        self,
        *,
        min_importance: ExperienceImportance = ExperienceImportance.MEDIUM,
        limit: int = 200,
    ) -> int:
        """Re-score a batch of experiences using the Significance Engine.

        Updates the stored ``significance_score`` in
        :class:`~subsystems.echo.models.ExperienceMetadata` for all
        eligible experiences without triggering full consolidation.

        Parameters
        ----------
        min_importance:
            Only re-score experiences at or above this tier.
        limit:
            Maximum number of experiences to re-score per call.

        Returns
        -------
        int
            Number of experiences whose scores were updated.
        """
        with self._lock:
            self._assert_running("integrate_significance_scores")

            _imp_order = {
                ExperienceImportance.LOW: 1,
                ExperienceImportance.MEDIUM: 2,
                ExperienceImportance.HIGH: 3,
                ExperienceImportance.CRITICAL: 4,
            }
            min_order = _imp_order[min_importance]

            updated = 0
            for exp in self._experience_engine.query_experiences()[:limit]:
                if _imp_order[exp.importance] < min_order:
                    continue
                try:
                    new_score = self._rescore(exp)
                    if abs(new_score - exp.metadata.significance_score) > 1e-6:
                        exp.metadata.significance_score = new_score
                        updated += 1
                except Exception as exc:  # noqa: BLE001
                    _logger.warning(
                        "Score update failed for %s: %s",
                        exp.experience_id,
                        exc,
                    )

            _logger.debug(
                "integrate_significance_scores: updated %d experience(s).", updated
            )
            return updated

    # ------------------------------------------------------------------
    # History & Audit
    # ------------------------------------------------------------------

    def get_cycle_history(self, limit: int = 10) -> list[ConsolidationReport]:
        """Return the most recent completed consolidation cycle reports.

        Parameters
        ----------
        limit:
            Maximum number of reports to return (most recent first).

        Returns
        -------
        list[ConsolidationReport]
            Cycle reports, newest first.
        """
        with self._lock:
            return list(reversed(self._cycle_history[-limit:]))

    def snapshot(self) -> dict[str, Any]:
        """Return diagnostic state for monitoring / debugging."""
        with self._lock:
            total_exps = 0
            consolidated_count = 0
            try:
                all_exps = self._experience_engine.query_experiences()
                total_exps = len(all_exps)
                consolidated_count = sum(
                    1 for e in all_exps if e.metadata.consolidated
                )
            except Exception:  # noqa: BLE001
                pass

            last_cycle = self._cycle_history[-1].summary() if self._cycle_history else None

            return {
                "running": self._running,
                "engine": "MemoryConsolidationEngine",
                "cycles_completed": len(self._cycle_history),
                "last_cycle_summary": last_cycle,
                "total_experiences": total_exps,
                "consolidated_experiences": consolidated_count,
                "policy": {
                    "low_retention_days": self._policy.low_retention_days,
                    "min_significance_for_medium": self._policy.min_significance_for_medium,
                    "prune_low": self._policy.prune_low,
                },
            }